### PR TITLE
Moves team member instruction here from onboarding repo

### PR DESCRIPTION
**Pull request by Frijol**
Getting rid of onboarding repo. Also a minor update to the contribution guide.

### CODE REVIEW

**Comment by Frijol** [comment]
Merge https://github.com/tessel/project/pull/200 when this lands so we don't have duplicated information

**Comment by tcr** [comment]
lgtm. What do you mean merge #200? This is 200.

**Comment by Frijol** [comment]
whoops, should have been https://github.com/tessel/onboarding/pull/19

**Pull request merged**
