### PR TITLE
Step 2 on boarding

### PR DESCRIPTION
**Pull request by Student007**

### CODE REVIEW

**Comment by Student007** [comment]
@Frijol fixed

**Comment by johnnyman727** [comment]
Whoops! We have a conflict. @Student007 can you rebase on master?
```
git fetch origin
git rebase -i origin/master
```

And bonus points for using the 'fixup' option to merge your commits into one.

**Comment by Student007** [comment]
@johnnyman727 close due to new PR https://github.com/tessel/project/pull/99

**Comment by johnnyman727** [comment]
@Student007 I'll check out your other PR but I am curious why you close this one to open a new one.

Perhaps you're having trouble pushing back up after you rebase? Because rebase changes the commit history, you need to force push (`git push origin master -f`). Then you don't need to open a new PR every time.

**Comment by Student007** [comment]
@johnnyman727 ... ah .. ok. I had some trouble with the stupid gui and deleted my fork. That is the reason I opened a new PR. I did it between other tasks and there was no time to find out how is the right way to come over the professional way - so  I used the axe ...

**Comment by johnnyman727** [comment]
Gotta kill that GUI!

**Pull request closed without merging**
